import intro from "./Basics/intro";
import materials from "./Basics/materials";
import text_3d from "./Basics/3d-text";
import lights from "./Basics/lights";
import hauntedHouse from "./Basics/haunted-house";
import particles from "./Basics/particles";
//intro();
//materials();
// text_3d();
//lights();
//hauntedHouse();
particles();
